spring:
  #配置数据源信息
  datasource:
    #配置数据源类型
#    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
##整合mybatis-plus
mybatis-plus:
    mapper-locations: classpath:com/maven/Mapper/*.xml
    type-aliases-package: com.maven.POJO
    #配置mybatis-plus日志
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        #配置mybatis-plus操作表的默认前缀
#        table-prefix: t_
        #配置mybatis-plus的主键策略
        id-type: auto

swagger:
  enable: true

#整合mybatis
#mybatis:
#  mapper-locations: classpath:com/atguigu/mybatisplus/mapper/*.xml
#  type-aliases-package: com.atguigu.mybatisplus.pojo
#  #配置mybatis日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


