spring:
  #配置数据源信息
  datasource:
    #配置数据源类型
#    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
#整合mybatis
mybatis-plus:
    mapper-locations: classpath:com/atguigu/mybatisplus/mapper/*.xml
    type-aliases-package: com.atguigu.mybatisplus.pojo
    #配置mybatis-plus日志
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
